# Generated by Django 5.0.3 on 2026-04-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KnowledgeBaseNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("source_url", models.URLField(max_length=500, unique=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content_raw",
                    models.TextField(
                        help_text="Original unedited content from the source"
                    ),
                ),
                (
                    "content_processed",
                    models.TextField(
                        blank=True,
                        help_text="Cleaned and AI-enhanced content",
                        null=True,
                    ),
                ),
                (
                    "embedding_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "embedding_vector",
                    models.JSONField(
                        blank=True,
                        help_text="Vector representation for RAG using MySQL JSON",
                        null=True,
                    ),
                ),
                (
                    "source_credibility_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Calculated credibility score from NLP/AI processing",
                    ),
                ),
                ("fail_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "kb_node",
                "ordering": ["-published_at"],
                "indexes": [
                    models.Index(
                        fields=["embedding_status"], name="kb_node_embeddi_a49494_idx"
                    ),
                    models.Index(
                        fields=["published_at"], name="kb_node_publish_fbfff1_idx"
                    ),
                ],
            },
        ),
    ]
