# Generated by Django 5.0.3 on 2026-04-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgebasenode",
            name="category",
            field=models.CharField(db_index=True, default="General", max_length=100),
        ),
    ]
