# Generated by Django 5.0.3 on 2026-04-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_base", "0002_knowledgebasenode_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgebasenode",
            name="full_text_scraped",
            field=models.TextField(
                blank=True,
                help_text="Complete article body extracted by the scraper",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="knowledgebasenode",
            name="content_processed",
            field=models.TextField(
                blank=True,
                help_text="Cleaned and AI-enhanced summary/analysis",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="knowledgebasenode",
            name="content_raw",
            field=models.TextField(
                help_text="Original unedited snippet from the source"
            ),
        ),
    ]
